export interface Chapter {
  title: string;
  paragraphs: string[];
}

// Text je prebraný z pôvodného listu — rozdelený do piatich kapitol,
// ale samotné odseky sú zachované presne tak, ako boli napísané.
export const chapters: Chapter[] = [
  {
    title: "Zmes pocitov",
    paragraphs: [
      "Ivetka snažil som sa to tu sformulovať nejak norlmne ale je tam väčší rozsah pocitov z viacerých dní a teda mieša sa tu viacero pocitov a nálad",
      "a nejde tu o žiadne vyzobranie tvojej pozornosti ani neviem či to vôbec uvidíš a či otvoris ale naozaj viem že je to moja a len moja vína čo sa stálo a to ako ti bolo a ako si sa trápila a bolo to len kvôli mne samému a mojej neschopnosťi komunikovať a riešiť problemi s tebou a mať chladnú hlavu a nebyť ako decko vo vzťahu a to som bol koľko krát",
      "ty si bola úžasná žena partnerka kamarátka q osoba ktorá bola vždy pre mňa a hrozné tj ďakujem zá to a ľúbim a navždy búdem",
    ],
  },
  {
    title: "Nič ti nedávam za vinu",
    paragraphs: [
      "ivet ešte by som ti chcel povedať toto, nič ale absolútne nič ti nedávam za vinu naozaj ani trochu.",
      "pokazil som to a to veľmi a neskutocnim spôsobom a veľmi to ľutujem a neviem s tým ani trochu žiť ale že vôbec viem ako ty vidíš ty vidíš má ako nejakého blázna ktorý sa zamotal do svojich klamstiev a je blázon ale je to úplne ináč",
      "je to tak že ja viem čo všetko som spravíl a ako veľmi som ti ublížil a ako hrozné ti muselo byť a veľmi neskutočne ma ničí tento pocit že si musela takto trpieť a že veľa krát som tí to ešte dával za vínu a veľmi ma to mrzí",
      "a naozaj viem že je to moja vína a viem že si za to môžem len sám a uvedomujem si to, a ver že nikdy som to takto nechcel nikdy len neviem vydržať pocit a situáciu za svoje činy q prepáč že som ťa toľko krát otravoval a aj keď som bol v absolútnych depkách a stavoch zhadzoval som to na teba",
      "je to moja vina ale naozaj to je také vyhrotene kvôli tomu že som prosté nevedel zvládnuť ani to že som ťa mal nechát vychladnúť a počkať kým sama napíšeš a zavoláš ale proste os momentu kedy som to pokazil tak je to len a len horšie a som v nesktocnom šoku a je to proste pre mňa trauma a prosté som to pokašľal a neviem to zniesť a žiť s tým čo som ja spravíl a to sám sebe a tebe tomu ublížil a mrzí ma to",
      "navždy ťa budem milovať a mať rád a záleží mi na tebe a nechcel som naozaj ťa zobrať a dopravovať sa ti ani vyplávať len úprimne sa porozprávať s tebou ako osobou ktorej som veľmi ublížil a zranil jej city",
    ],
  },
  {
    title: "Zúfalstvo v jednom dychu",
    paragraphs: [
      "kľudne dobre pošli k tomu mu chceš nech má každý označí ako chce nech ma to už zničí všetko lebo to si len zaslúžim a už nemôžem ďalej jeden na to dnes proste bola fakt úžasná žena úžasná fakt a ja nemôžem počúvať to jak som týral a šikanoval a Bill keď viem že som spravil veľa chyb ale nebol som taký ja ťa hrozne ľúbim a už sa zbláznim z toho prisámbohu prisahám bohužiaľ už sa zbláznim úplne ja už nemôžem ja som ťa poprosil naozaj ja viem jak to vyzerá ale ja som ťa prosil ja som sa chcel fakt normálne porozprávať a keď ty ty sa nevieš na mňa ani pozrieť a zavolať mi tak čo musím ja byť za skurveného človeka pojebaného čo ja musím byť skurvený hajzl fakt tým my nevieš ani zavolať sa neznášam v hrozný človek hrozný hnusák nemám nič nemám sa ani rád čo ste ja myslím celé dni len na teba natočil som ti spôsobil a nedokážem proste s tým isť ďalej nejak bola si to najlepšie čo mám mohol v živote stretnúť a neviem nič už nezaslúžim si nič za všetko naozaj ľúbim ľutujem ver že že ľutujem všetko ale už nevládzem nemôžem a nedávam to čo mám v hlave už nemôžem ani kľudne ani hnusnú hodinu zvládnuť doma neviem už bych tam šibe a proste nedávam to nezvládám prosím ťa prosil som ťa ja viem čo som spravil ale keď tak normálne ma neznášaš ja nemôžem že existovať",
    ],
  },
  {
    title: "Tichý dovetok",
    paragraphs: [
      "Ivetka naozaj prepáč je to moja vína prepáč že som ti zlomil srdce",
      "a ak náhodou si niekomu niečo preposiela neviem to potvrdiť je to len otázka tak snáď si to mohla chápať aj ako len to že mi šibe z mojej vlastnéj chybi a dúfam že už tak z celim kontextom si to preposlala",
      "ja neviem naozaj neviem to je len otázka ja neviem na sa tu doma zbláznim naozaj neviem",
      "mňe to je ľúto naozaj všetko by som spravíl aby si vedela že mi to je ľúto a že som úprimný ku tebe je mi ro ľúto naozaj a mrzí ak to je tak a že takto neľudský musíš pristupovať ku mne ak to je tak to je len neviem ani čo teória neviem",
      "a prepáč že som taký a že som bol asi lutujes že si ma spoznala a mrzí ma to že dačo také lutujes zrejmé prepáč mi to ale nechápem prečo stále doma neverím nikomu nechápem tomu čo tu sa deje ale nejdem nič ja riešiť teráz pokúsim sa z chladnou hlavou a na konci už ked bude najhoršie tak fakta vytiahnuť ale to je jedno len prosím ten jeden par minutovi hovor prosím ťa o to ďakujem",
      "a ľutujem vecí aj ktoré som napísal aj keď v absolútnom šialenstve ale ľutujem len keby si naozaj malá možnosť tu byt alebo skor v  mojej hlave tak pochopíš a ked to je tak ako apm počul tak ma to mrzí veľmi",
    ],
  },
  {
    title: "Prosba na začiatok",
    paragraphs: [
      "naozaj prosím venuj mi prosi5len chvíľku tvojho času a prosím ťa reálne a úprimne si to prečítaj vklude veľmi mi na tom záleží ale chápem že že po tom všetko dl som spravil nie je veľmi podstatné to na čom mne záleží a uvedomujem si to",
      "skúsil som to spraviť takýmto prezentačnim spôsobom keďže asi kopa textu takto môže pôsobiť nepríjemné zdĺhavo qle prosím je to naozaj pre mňa dôležitá a neskutočne mq to trápi celé sni q noci veľmi ťa mam rad a ľutujem to všetko naozaj všetko neskutočne veľmi to ľutujem mám ťa veľmi rád naozaj veľmi a prosím len si ro prečítaj prosím",
      "a Ivetka neskutocne veľmi mi chýbaš a ak tvoje prítomnosť a dobrá duša a je mi ľúto toho čo som spravil a ako som ublížil a zničil neskutočne ma to trapy, a chcel by aom ťa požiadať aby si si len prečítala tento e-mail, nie je v ňom nič zlé naozaj nie",
      "prosím ťa už len kvôli tomu keď si mám naozaj mala niekedy rada prosím len mi nedávaj to hnedka do koša a prosím prečítaj si to naozaj mi na tom veľmi záleží",
      "a uvedomujem si že na prvý pohľad takáto správa môže pôsobiť dlho naozaj prosím ťa nedávajú do koža nie je nič nič lepne ja nebola písaná zlo absolútne žiadnym zlým úmyslom alebo nejakým neviem podobným úmyslom ktorý je podobný tomu zlému naozaj nie",
      "a ver mi že spravím všetko naozaj všetko co zvládnem aby som ti ukázal ze mi to je ľúto a že to ako som sa s tebou bavil som nemyslel vážne a že som bol len kretén ktorý nechal svoje pocity a zlé nalady prasknúť a veľmi to ľutujem den co den naozaj veľmi",
      "a naozaj všetko fakt čo je tu napísané je normálne nie je tam proste nič eh zlé škaredé alebo neviem aké je mi smutné že to takto musím písať ale naozaj väčšine predošlých e-mailov tomu tak bolo až na nejaký výnimky za ktoré sa hanbím a blutujem ich že som sa nechal tam dotlačiť k svojim zúfalstvom šialenstvo",
    ],
  },
  {
    title: "Úprimne, bez ozdoby",
    paragraphs: [
      "a proste je tu len skratke minimálne popísané to ako sa cítim a to všetko čo sa stalo a všetky vecí ohľadom toho ako vnímam a mrzí ma to naozaj eh môže sa stačiť tu je veľa chyb a nesúvislých slov ktoré nedávajú význam za čo sa ospravedlňujem a dúfam že ťa to neodradí od toho aby si si to dočítala čo ti budem veľmi vďačný",
      "ja viem že už asi vyzerám hrozne zúfalo alebo hlúpol naozaj je pravda to že som hrozne zničený a zúfalým takže vlastne to jak vyzerám áno proste neviem už čo ďalej a viem že nemám žiadny nárok na to že by som vôbec mohol žiadať aby si si to prečítala ale dúfam že aspoň niečo to málo dobre čo bolo si pamätáš ani nezabudla si na to",
      "a naozaj nikdy som nemal ani čo ich len ten najmenší plán alebo nápad ti nejak u škodiť alebo ublížiť alebo zraniť tvoje city a naozaj veľmi prosím ťa neskutočne mám boli a trápi to ako som si ublížil a zranilca a veľmi že to myslím vážne lebo už som z toho fakt na dnem ako človek ako ľudská bytosť úplne zničený a som úplne zúfalý zo všetkého a neviem čo ďalej takže viem mi prosím že naozaj ma tu trapy",
      "veľmi si želám aby si si to prečítala naozaj sú to úprimné slová možno to niekde znie čudne alebo je to skrumované alebo neviem ale naozaj som sa snažil proste tu napísať úprimne a čo najviac autentický alebo ako ináč to nazvať neviem proste naozaj mi na tom záleží a aj na tebe mi vždy záležalo a mrzí ma všetko čo sa stalo",
      "a uvedomujem a viem že niektoré emaily čo prišlím mohli byť trochu prudké alebo nemoc pekné ale viem že naozaj po tých emailoch čo boli hneď v ten moment čo boli hrozné a hanbím sa za ne a hrozne ma trápiť čo som tam napísal tak nebolo v iných emailoch naozaj nič čo by sa urážalo alebo nejakým iným spôsobom napadal ale to je jedno vlastne",
      "ale nechcem aby si vedela že naozaj aj tie emaily čo boli prudké alebo aj tam by som bol veľmi škaredý tak som ich písal v absolútnom šialenstve a zrútení a neviem ani ako to napísať bez nádeji alebo neviem čum inom jak sa to presne názve ale pustil úplne som bol mi moc viem že to nie je ani zďaleka a ani trochu ospravedlnené za to lebo už som ich proste napísal uvedomujem si to len proste dúfam že vieš že tie veci ako tam boli napísané tak nemyslel som tak že vieš že proste keď je človek nevie tak vie povedať niečo čo veľmi ľutuje a nie to ešte keď príde o prispôsobu ako som prišiel ja proste naozaj viem že sa to nedá ospravedlnený tak to určite ale naozaj pustí je mi to veľmi ľúto a mrzí ma že som to takto vôbec napísal a že som dovolil proste hnev a zrútenie tak to mi dobre zľavu že som dokázal také veci napísať",
    ],
  },
  {
    title: "Spomienky a moje chyby",
    paragraphs: [
      "a nikdy nezabudnem na ten deň keď som ťa spoznal bol to ten najlepší deň v mojom živote prvý s tebou a ver mi že keby existoval nejaká možnosť ako to vrátiť tak ju rovno beriem a vrátim sa do toho dňa a veľmi veľa vecí by som spravil úplne ináč aku veľa veca by som úplne ináč prístupoval a veľmi by som si to vážil a plus šťastných zato keby to bolo možné a reálne len bohužiaľ nie je to možné na to žreálne ale keby tak rovna to beriem ale bohužiaľ niekde to ale je mi veľmi ľúto to čo sa stalo a veľmi som študovanie šťastný a veľmi mi chýba a proste tvoja prítomnosť vzruštom si nevážil aha ktorú som zničil",
      "ja viem že proste aj počas toho keď sme boli spolu veľakrát som niečo sľúbil napríklad a že som úplne splnilo alebo zabudol ale veľmi že nikdy som to nerobil naschvál a vôbec som si to nedávna neuvedomoval ako rýchlo plynie čas a ako rýchlo obiehajú dni a proste všetko sa mi to dávalo do jednej koupím a vôbec som nemal prehľad o tom čo treba spraviť čo je povinnosť čo netreba koľko ubehlo od toho od toho a proste ste úplne úplne som neviem neviem žil ako keby zrychlenom režime alebo neviem ako to opísať ale to je jedno a teraz až v posledné týždne si uvedomujem že aký je dlhý deň a že proste naozaj som veľakrát tie možnosti aj cez ten deň aj keď som mal povinnosti alebo zelená ľady alebo pocity z toho že nestíhám alebo že mám malú peňazí alebo problémy tak aj cez toto všetko boli proste body počas nejakédí som mohol kľúče a dostatočne aspoň nejaké tie sľuby splniť a tým pádom ich dodržať naozaj je mi to je veľmi ľúto že som bol taký hnusný človek čo nedodržal ani to najmenej",
      "a naozaj je mi z toho všetkého na nič úplne na nič ešte nikdy ani vzdialené som sa necítil takto ako teraz lebo ako teraz je to hrozné neviem vklude byt doma počujem samé hlúposti ktoré neviem ci su alebo nie sú skutočne ale problém je že ich počujem nikomu doma neverím všetkých obviňujem a uplne som už šialený naozaj normálne c poslednej dobe to najviac neznášam doma a je to najhoršie miesto ktoré poznám a kde travim čas a xxx krát za deň radšej idem na aute na parkovisko do rohu a tam sedím v aute kde je ticho a nie je tam niekto a nemusím sa báť že mi niekto niečo spraví alebo si bude niečo myslieť alebo hovoriť nikomu na mňa niečo",
      "a naozaj ma mrzí hlavne aj to o no nie že hlavne ale aj to že aj napríklad tá tá stránka že proste nepozrela ani a bolo to veľmi že viac než len stránka dal som fakt do toho časová fakt som sa snažila aby proste ti to zmenilo proste život kancelária digitálna ale to je jedno len proste má to tiež mrzí ako jedna z malá vecí ale ako môžem si za ňu sám ako to je tiež pravda on mi to teraz tak prišlo ľúto tak neviem čo tu ale naozaj proste je mi to ľúto Ivetka",
      "a neviem už naozaj kto som posledné dní sa nespoznavam vôbec sa necítim ako keby som to bol ja, úplne šaliem z toho keď je niekto doma a som úplne presvedčený ze rodičia na mňa niečo chystajú a celý čas počujem ako ma ohovárajú a niečo chystajú a snažia sa zo mna spraviť zrejmé chorého človeka ktorému zoberú práva a strčia ho nikde, a celé noci som úplne vystresovaní z toho ze mu tu niekto vybehne alebo niečo sa niekto pokúsi spraviť uz neviem co mam robiť naozaj neviem, a keď sa pýtam tak len ze oni nič nerozprávali a snažia sa zo mna spraviť blazna a len počujem ze som debil, chory, blazon, sialeny, nezmiselny, hlúpy a že som len sklamané a je mi z toho zle už naozaj, a tento dom je prekliatie naozaj vždy počujem dačo a všade nechápem tomu",
      "a dal by som úplne všetko naozaj aj niektorých členov rodiny by som vymenil za to aby som všetko mohol vrátiť do momentu ked sme bolí v Bratislave a úplne by som vela vecí spravil inak a vela chýb by som sa pokúsil napraviť aj keby skm mal možnosť sa vrátiť len do bodu ked sme tam boli posledné 4 týždne aj tak by som spravil všetko co je v ľudských silách na to aby tp bolo inak ale bohužiaľ toto su len sny a nereálne vecí ale to je jedno najdôležitejšie je to co je teraz a teraz je to že som uplne všetko zničil najdôležitejšie pre mna to ze som pokazil a ranil tvoje city mojím nepristupnim správaním a tym ze som upadol do chaosu kde sú len dlhy problémi a moje chiby ktoré ma dohnali do bodu keď som to prehnal a ľutujem to naozaj veľmi potom doma vzťahy vôbec im neverím ale ze vôbec ani slovo, o vela kamarátov som prišiel fo ma tiež mrzí, ani zo súrodencami nevychádzam a v konečnom dôsledku nemám nič a nikoho",
    ],
  },
  {
    title: "Zúfalstvo a túžba povedať to",
    paragraphs: [
      "a už mi je naozaj veľmi hrozné z tpho všetkého a z celej situácie čo je a čo sa stala, snažím sa naozaj snažím sa držať nejako mať nadhľad ešte nejaký ale aj doma to ako pristupujú ku mňe ma tiež ničí neskutočne veľmi a ked vidím tie vyrazí a ako sa snažia mi len vnútiť nejaké tabletky a spravit5zo mňa nejakú osobu ktorá už nemá pocity ani nič norlmne v hlave len tabletky tak naozaj mi je na nič a som hrozné nešťastný zo svojho života a toho ze nesmeruje nikam a keď už tak l3n smerom z ktorého by bol nešťastný asi každý človek a naozaj ma mrzí každa vec situácia ktorov som ti mohol alebo spôsobil nepríjemné pocity a tým pádom som ranil tvoje city a úprimne mi to je naozaj ľúto a vekmi5ma to mrzí",
      "a veľmi hrozné moc by som sa chcel s tebou l3n porozprávať a povedať ti všetko q myslím to naozaj vážne a naozaj normálnym spôsobom úprimne a b3z nejakých vycitok alebo zlých pocitov, a je mi ľúto a hambym sa za to že ked si sa snažila tak som to všetko držal v sebe a tváril sa ako keby nič ze všetko je v pohode a pritom som relane trpel a bol nešťastný a sklamaný zo života , a ver mi ze mi to je naozaj ľúto q veľmi ma to mrzí celé a uz len pri pomisleni som ešte viac nešťastný ale to je teraz nepodstatné, prosím iveta ver mi ze naozaj v živote nidky by som ti nechcel uškodiť alebo ti ublížiť naozaj nikdy, a ranil som ta veľa krát na čo nie je ospravlnienie ale ver mi nidky som to neurobil zámerne co nie je tiež ospravelnie ale naozaj už nikdy sa to nebude opakovať nechcem.sa už naozaj prebúdzať do takýchto dní plných depresiie a zúfalstva a smútku, a naozaj mi môžeš veriť už nikdy ai nedovolím toto ku tebe a niekomu inému, hrozné moc veľmi ta mám rád a záleží mi neskutočne na tebe, a ľutujem že som ublížil milovanej osobe ktorá mi je neskutočne veľmi blízka",
      "a proste tak by som sa chcel s niekým porozprávať veľmi celé tie týždne proste som sa s niekým ani neporozprával o ničom ale ale vlastne ani nemám s kým proste všetci len stále alkohol ako kokotiny chápeš a vôbec nechcem ísť s tou cestou teraz ešte v tomto a v týchto stavoch eh alkoholu a proste teraz len urobiť niečo čo budem ľutovať nie je podľa mňa najlepšia tie staré riešenie a proste nechcem proste s takými ľuďmi teraz tráví čas aj keď sú to kvázi niektorý môj kamaráti ale načo neviem neviem proste taký človek mi nepomôže keď online stále rieši to že sa mám napiť a napiť a napiť tak takéto človek mi sotva pomôže no ale to je jedno aj tak proste naozaj mi to je ľúto Ivetka a veľmi ani si fakt nevieš predstaviť ako veľmi ľutujem to čo som spravil a aj všetky tie momenty ktoré som mohol dať celkové celkový náš vzťah k využiť ináč a mať omnoho viac pekných spomienok",
      "a prosím ver mi že nemám ani ten najmenší zlý úmysel naozaj, a naozaj sa chcem len normálne porozprávať a dúfam že voči mne máš aspoň nejaké minimom ale dobrých spomienok a pocitov teda skôr v to dúfam a dúfam že som nebol celé 4 roky taky zlý človek ako sa cítim posledné dní že som a naozaj ma to mrzí všetko a neskutočne sa cítim zlé a hrozné a nesvoj naozaj ako keby som nebol ani vo svojom tele a sebou Lebo neskutočne mi je, a Ivetka prosím ver mi že nie som plačko naozaj nie a to že dpatanme nejaký panicky záchvat zúfalstva nie je podla mna plačko ale akor to je len vedomí pocit toho ako som zlihal2v každom smere a ako som všetko pokazil a ako som o všetko prišiel a stal sa človekom čo nemá nič a niekoho a naozaj mi je z toho hrozné a som veľmi nešťastný z toho ako som všetko zničil a pokazil a koľko som mal možnosti",
      "a proste viem že už to nikdy nebude asi také ako to bolo aj keď by som si to hrozne prijal ale uvedomujem že ste mi tak vzniká vznikli následky ktoré už sa asi nedajú zvrátiť a veľmi že to ľutovať celý život a že mi na tom proste vždy ďaležalo a záležím a tým myslím teba a naozaj som si prijal ci vďačným ďakoval keby si si našla na mňa na chvíľu času ale len normálne si zavolali naozaj normálne nič fakt naozaj žiadna hádka nič len proste normálny telefonát normálne sa len porozprávať normálne by som sa chcel opýtať pár vecí pár vecí proste zodpovedať ale len proste normálny telefón dať naozaj žiadna hádka žiadny konflikt žiadne vyčítanie žiadne neviem nadávky nič proste naozaj len proste normálnych telefónát normálnych ľudí naozaj",
      "Ivetka prosím ťa ver mi že naozaj mi tvoje ľúto viem že ťa nemám o čo žiadať a že nemám ani to najmenšie právo proste niečo po tebe chcieť alebo čakať",
    ],
  },
  {
    title: "Posledná prosba",
    paragraphs: [
      "ale naozaj ťa veľmi prosím a žiadam o chvíľu tvojho času a telefón nad naozaj veľmi prosím ťa nechcem ti nijak škodiť prosím že už už sa cítim hrozne lenže to musím hovoriť lebo nikdy som ani nechcel",
      "chcem sa len normálne ale že normálne porozprávať normálne naozaj viem že veľakrát sme sa pohádali cez telefón alebo proste si vyčítali alebo vykríčali niečo uvedomujem si to a viem že je väčšinou som to spôsoboval ja teda väčšinou skoro vždy a je mi to naozaj veľmi ľúto",
      "nechcem sa hádať nechcem si nič vykrikovať nechcem si zničí vyčítať nechcem proste robiť nejakú dusnú náladu alebo atmosféru naozaj prosím určite to nechcem a prosím ťa ver mi že nikdy som ani nechcel a ani som to nemal v pláne a veľakrát sa to stalo a je mi to naozaj veľmi ľúto a trápi ma to ako som to spôsobil veľakrát len svojou tvrdohlavosťou alebo zlým postojom",
      "ale naozaj sa chcem len veľmi normálne porozprávať nič viac naozaj nečakám že budeš na mňa milá alebo sa nejako nesmierne tešiť a na mňa ale len sa chcem fakt normálny porozprávať viem že to vieme obidvajam a vždy sme sa vedeli normálne porozprávať a viem že som ti veľakrát ublížil mojim správaním ale verím v to že si nezabudla na toho ako sme sa vedeli vždy normálne porozprávať pas ku koncu sadcotalo rozpadať a bohužiaľ málokedy sme sa normálne porozprávali",
      "ale vždy sme v tom vedeli a ja nezabudnem nikdy na tie dni keď sme je to vedeli robiť a rozprávať sa normálne celé dním a smiať sa a na tvoj úsmev ale na tvoje krásne oči len teraz si povieš ku k tomu tomuto že to je ale trápne alebo hrané možno trochu áno neviem som to nemyslel ako nejak tak tak že alebo čakal že ťa tým nejak dostanem do kolien to určite nie",
      "a veľmi proste dúfam a žiadam a dúfam ani neviem jak to nazvať čo čakám len prosím nájdi si tú chvíľu na mňa aj naozaj neviem ani žiť neviem nič robiť neviem sa sústrediť celé dni neviem proste s niekým vychádzať zo všetkými som rozhádaným kamoší niektorí sa so mnou prestali až baviť ja viem že to je moja vina len proste neviem ani fungovať ako človek normálnym neviem proste nič robiť neviem ani mať žiadny dajaký nápad že váhu ani nejaký cieľ ani proste niečo čo chcem napríklad urobiť v ten deň keď sa zobudím že čo mám proste na pláne a čo by som chcel proste nič nemal naozaj nič",
      "ale naozaj ťa veľmi prosím a žiadam o chvíľu tvojho času a telefón nad naozaj veľmi prosím ťa nechcem ti nijak škodiť prosím že už už sa cítim hrozne lenže to musím hovoriť lebo nikdy som ani nechcel",
      "chcem sa len normálne ale že normálne porozprávať normálne naozaj viem že veľakrát sme sa pohádali cez telefón alebo proste si vyčítali alebo vykríčali niečo uvedomujem si to a viem že je väčšinou som to spôsoboval ja teda väčšinou skoro vždy a je mi to naozaj veľmi ľúto",
      "nechcem sa hádať nechcem si nič vykrikovať nechcem si zničí vyčítať nechcem proste robiť nejakú dusnú náladu alebo atmosféru naozaj prosím určite to nechcem a prosím ťa ver mi že nikdy som ani nechcel a ani som to nemal v pláne a veľakrát sa to stalo a je mi to naozaj veľmi ľúto a trápi ma to ako som to spôsobil veľakrát len svojou tvrdohlavosťou alebo zlým postojom",
      "ale naozaj sa chcem len veľmi normálne porozprávať nič viac naozaj nečakám že budeš na mňa milá alebo sa nejako nesmierne tešiť a na mňa ale len sa chcem fakt normálny porozprávať viem že to vieme obidvajam a vždy sme sa vedeli normálne porozprávať a viem že som ti veľakrát ublížil mojim správaním ale verím v to že si nezabudla na toho ako sme sa vedeli vždy normálne porozprávať pas ku koncu sadcotalo rozpadať a bohužiaľ málokedy sme sa normálne porozprávali",
      "ale vždy sme v tom vedeli a ja nezabudnem nikdy na tie dni keď sme je to vedeli robiť a rozprávať sa normálne celé dním a smiať sa a na tvoj úsmev ale na tvoje krásne oči len teraz si povieš ku k tomu tomuto že to je ale trápne alebo hrané možno trochu áno neviem som to nemyslel ako nejak tak tak že alebo čakal že ťa tým nejak dostanem do kolien to určite nie",
      "a veľmi proste dúfam a žiadam a dúfam ani neviem jak to nazvať čo čakám len prosím nájdi si tú chvíľu na mňa aj naozaj neviem ani žiť neviem nič robiť neviem sa sústrediť celé dni neviem proste s niekým vychádzať zo všetkými som rozhádaným kamoší niektorí sa so mnou prestali až baviť ja viem že to je moja vina len proste neviem ani fungovať ako človek normálnym neviem proste nič robiť neviem ani mať žiadny dajaký nápad že váhu ani nejaký cieľ ani proste niečo čo chcem napríklad urobiť v ten deň keď sa zobudím že čo mám proste na pláne a čo by som chcel proste nič nemal naozaj nič",
      "a chcel by som ťa ivetka požiadať o možnosť sa s tebou porozprávať normálne, ver mi prosím ťa že mi to je naozaj ľúto a veľmi ma to mrzí q ničí čo som spravil a nedokážem celé dni kvôli tomu ani späť ani žiť viem že je to moja chýba q plné si to uvedomujem to mi prosím ver ale neskutočne ťa mám rád a záleží mi na tebe a neviem si ani len predstaviť život z vedomím že som o teba prišiel a ešte takýmto spôsobom a mpjou vinou úprimne a naozaj som sa poučil a neskutočne tl ľutujem každý deň ci noc a veľmi mi je ľúto že osobe ktorú neskutočne mám rád a záleží mi na nej neskutočne veľmi som takto ublížil a ranil jej city prosím ver mi že už sa to nikdy nebude opakovať a nikdy nedopustim aby moja chybi a problémi vo mňe dokázali spraviť to ze sa budem takéto správať a že zraním blízku osobu naozaj nikdy už sa to nebude opakovať len tá prosím veľmi ťa prosím za všetko na svete prosím neodchadaj mi zo života a nerob mi to prosím naozaj už nikdy nepsravim takuto chybu a skutok prosím Ivetka naozaj ťa mám veľmi rad a spravím čokoľvek aby si videla ze to tak je a ze mi to je neskutočne ľúto,, naozaj už nechcem takyto dwpresnoivni život a vedomie prosím naozaj mi to je ľúto a len možnosť prosím mi daj a zavolaj mj prosím len sa chcem normálne úprimne porozprávať veľmi ťa mám rád a prepáč mi to všetko naozaj",
    ],
  },
  {
    title: "Volanie o pomoc",
    paragraphs: [
      "prosím ťa ivet mohla by si mať malé zľutovanie nado mnou prosím ťa ja viem že vína je moja a netvrdil som opak, tak prosím ťa naozaj som úplne v pi... z domu mám ísť preč, pešo mám ísť od autá ktoré sa komplet pokazilo najhorším spôsobom nemám žiadneho kamoša kde ísť ani rodinu ktorá by má zobrala ku sebe,",
      "tak prosím ťa mohla by si mi zavolať prosím si jediná osobám a človek ktorého mám a je veľmi dôležitý pre mňa prosím Ivetka veľmi nemám nikoho",
      "a ja tak ako aj dnes aj v tých vyhrotených správach ale aj tam som jasné a tak ako je hovoríl že ťa mám rád a záleží mi na tebe veľmi prosím mohla by si mi pomôcť veľmi ťa potrebujem",
    ],
  },
  {
    title: "Špička ľadovca",
    paragraphs: [
      "ja viem že som ti povedal že skúsim vydržať čo najdlhšie ale Amy tak hrozne z toho čo som ti napísal z toho všetkého čo sa stalo z toho aký som bol k tebe z toho ako som si dovolil sa k tebe správať a to len kvôli tomu že ja som bol utrápený mal som toho veľa a mal som depky tak som si dovolil takúto hlúposť spraviť ktorú tak hlutujem a tak má ničí že že mi je tak hrozne úplne mi je na hovno mrzí ma to že som si dovolil toto k tebe ale nie len toto aj všetky tie veci predtým tie nálady tie výčitky to aký som bol proste nepríjemný a koľkokrát som ťa proste volal von a pritom som ti len pokazil na ľadu v deň aký som bol si ma to že som bol taký sobecký a zlý a že za to že ja som bol utrápený tak som to prenášal na niekoho iného a robil mu zlú energiu a zlé pocity a je mi ľúto že keď si mi dávala možnosť sa porozprávať takže som mu nevyužil každý deň nad tým premýšľam každý deň nad tým keď si mi dávala možnosť mala záujem chcela piť pre mňa a ja som toho odmietal lebo som sa snažil hrať nejakú društvu tvár alebo neviem každý deň toľko ľutujem každý deň chýbaš mi viem že nikdy by sme už asi netvorili pár lebo som to veľmi pokašlal a veľmi som ti ublížil bolestivé a každý deň ma to kvôly a mrzí ale je to proste je moja vina že to tak už zrejme nebude ale chýbaš mi ako človek ako osoba ktorá sa zaujímala a mala má ráda ako super človek ktorý",
      "a mrzima bol taký zbabelec slaboch ktorý nevedel sa rozprávať o svojich problémoch a myslel si že je čudné ich mať je mi ľúto že som nas zničil k tebe zobral rokým a urobil ťa nešťastnou a najviac mi chýpať ten výraz ktorý si mala to je ten ktorý znamenajú sa zaujímáš a máš máš ma rada je to ten najlepší výraz ktorý som videl Bola si taká super si my chcela dobre vždy si proste sa snažila pre mňa a ja som to veľakrát zničil apokazil a ty si bola na toľko úžasná že si mi dala ďalšie šance a to je úplne super a už len to ukazuje ako veľmi si ma milovala a ja som bol taký hlúpy hlupák že aj tak proste som stále chcel nejaké pivo alebo v nejakú hlúposť a nevážil som si to najlepšie a najdôležitejšie čo som mal a mohol mať a čo môže mať človek a to je partnera ktorý ho úprimne miluje a to si bola ty a ja som to proste zničil a teraz vlastne už ani neviem koľko to je mesiacov nepijem nič ani ma to nejak neťahám a keď si predstavím že koľko šanci som premárnil na alkohol tak mi je hrozne privedomíš že teraz som úplne na dnes zničený zúfalým vyčerpaný zo seba samého a chýbaš mi a dal by som teraz všetko za jednu šancu možnosť a vedel by som že už to nebude zle už to nebude také ako to bolo a a pri pomyslení že koľko som tých šanci premárňujú na to že som to pokazil alkoholom je hroznil je mi hrozne a nemám sa za to rád čo som spravil a koľkokrát som to spravil nemám sa za to rád nenávidím sa za to lebo lebo ty si proste bola aj si môj vesmíru a postavil som si všetko na tebe a s tebou a proste keď ťa nemám nemám nemám ani sám seba ani svoje sny ani ciele ani to čo som chcel dokázať nemám nič sám som seba zničil a tebe ublížil",
      "a veľmi to ľutujem každý deň toho toho a nielen kto posledné čo sa stalo to bolo už len špička ľadovca ľutujem všetky tie momenty ktoré som pokazil všetky situácie ktoré som spravil všetkým problémy ktoré som spravil to že som ti to doma pokazil že som tam vystrelil to čo som vystrelil tým som proste začal to že náš vzťah som kriticky zasiahol a toho momentu by som sa chcel vrátiť naspäť ho opraviť tu nič iné by som si nežaloval viac vymenil by som za to všetky získané vedomosti všetko by som za to vymenil a len aby som sa tam mohol vrátiť a spraviť tvoj ináč a.s vtedy ku tebe do izby a nesedieť tam ani nalieva do seba hlúpy debilní alkohol ktorý mi nikdy nič nedal a vždy mi zobral len viacej nikdy mi nedal nič nedal mi ani zábavu lebo to si mi dal zábavu nejakú tak mi akurát aj zobral viac samého seba všetko na svete by som dal za to aby som sa mohol tam vrátiť a byť s tebou v tej izbe a byť spolu a nie sedieť v von a liať seba jak imbecil",
      "teraz by som dal všetko len na to aby si mi zavolala aby som ti to mohol úprimne povedať aby som sa s tebou mohol úprimne porozprávať a povedať a zodpovedať ti všetko na čo sa budeš pýtať bez toho aby som niečo zatajovať alebo hrať nejakú formou alebo hovoriť že mi nič nie je aj keď viem že mi niečo je ľutujem to že proste aj v tých správach proste som ta obviňová z vecí za ktoré nemôžeš a že som proste si vymýšľal teórie a situácie ktoré sa nestali a za ktoré nemôžeš nie je proste tvoja vina a ja som na vine práveže a stáva sa zo mňa pomaly blázon Lebo tak veľmi ťa mám rád a tak veľmi si pre mňa dôležitá a nedokážem žiť s vedomím pocitom že ako veľmi som to pokazil a ako veľmi som ti ublížil a ešte pri vedomie že koľko šanci som premárny u na hlúpom alkoholem je hrozne a nechutne vôbec existovať ako človek si to najlepšie čo som mal a mohol mať a už nikdy nebudem môcť mať niečo také úžasné v živote a mať takú úžasnú partnerku a človeka ktorý sa o mňa zaujímam a chcem ísť úprimne dobre je mi úplne hrozne z toho že som to takto pokazil úplne mi je na nič z toho že proste šálem úplne šalým zostávám sa proste dostával na depresii proste a potom píšem pustiť ktoré ani nechcem písať len mi je úplne na nič úplný mi je zle cítim sa hrozne bezmocne a sám mi chýbaš veľmi všetko by som dal dať toho missi mi dala len možnosť je rozhovorov neskutočne všetko by som za to dal je mi ľúto že som ti ublížil а mám ťa veľmi rád ľúbim aj keď viem že už nikdy nebudeme zrejme tvoriť s pár aj keď to bola neskutočný super vec to to možnosti ešte raz bol by som kokos najšťastnejší človek na svete šťastnejší už ani nemohol že niekto byť ale zrejme to je len v môj sen ale chcel by som ťa proste mať naspäť ako osobu ktorá sa zaujímam a ma.ma rada a záleží je na mňa Toto by som si prijal",
      "a ľutujem včera tie správy bolí to moje pocity bolo ni hrozné čo aj stále je alw naozaj som sa ri nevyhrážal ničím len som úplne zničení z toho čo som spravil a len svojou vinou q neviem to zvládať Lebo proste naozaj mi je veľmi ľúto toho čo som spravil a že som prišiel o teba a že som ti ublížil a zranil tvoje city ako osoby ktorá bola vždy pre mňa q snažila sa a vlastné tý ai aj bojovala za nas pri tom čo ja som si myslel že ja som ten co bojuje za nás je mi ľúto ako som to spravil a co všetko som napáchal a zarobil a ver mi že viem že to je moja vína a naozaj to ako som tu salel je ken ukážka toho že neviem normálne zniesť svoje následky za svoje činy",
    ],
  },
];
